version: '3.0'
services:
  app:
    # If a context is not provided Docker looks for a file named "Dockerfile"
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - 8080:8080
    depends_on:
      - app
